# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
- "alerts/*.yml"

scrape_configs:
- job_name: 'spring-boot-services'
  metrics_path: '/actuator/prometheus'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [ __meta_kubernetes_pod_annotation_prometheus_io_scrape ]
    action: keep
    regex: true
  - source_labels: [ __meta_kubernetes_pod_name ]
    target_label: pod

- job_name: 'ml-services'
  metrics_path: '/metrics'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [ __meta_kubernetes_pod_label_app ]
    regex: 'prediction-service|credit-risk-service'
    action: keep

- job_name: 'node-exporter'
  static_configs:
  - targets: [ 'node-exporter:9100' ]
